name: Test plugin

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: 0 0 * * 5

jobs:
  test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@v1

      - name: Test plugin
        run: |
          asdf plugin-add ccache $GITHUB_WORKSPACE
          bats test
        env:
          GITHUB_API_TOKEN: ${{ github.token }}
